# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: unit-tests
          command: npm test
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
